name: healthcare_secure_data_platform
version: 0.1.0
config-version: 2

profile: healthcare_secure_data_platform

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets: ["target", "dbt_packages"]

quoting:
  database: false
  schema: false
  identifier: false

data_tests:
  healthcare_secure_data_platform:
    +store_failures: true
    +schema: quality

models:
  healthcare_secure_data_platform:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
    curated:
      +materialized: table
      +schema: curated
      core:
        +schema: core
        +tags: ["milestone_6", "core"]
      billing:
        +schema: billing
        +tags: ["milestone_8", "billing"]
      finance:
        +schema: finance
        +tags: ["milestone_8", "finance"]
    marts:
      +materialized: table
      +schema: mart
    semantic:
      +materialized: view
      +schema: semantic

vars:
  healthcare_platform_execution_mode: local
  raw_clinical_database: HEDP_DEV_RAW
  raw_clinical_schema: CLINICAL
  raw_operational_database: HEDP_DEV_RAW
  raw_operational_schema: OPERATIONAL
  raw_audit_database: HEDP_DEV_RAW
  raw_audit_schema: AUDIT
  raw_quarantine_database: HEDP_DEV_RAW
  raw_quarantine_schema: QUARANTINE
  raw_interoperability_database: HEDP_DEV_RAW
  raw_interoperability_schema: INTEROPERABILITY
  raw_billing_database: HEDP_DEV_RAW
  raw_billing_schema: BILLING
  raw_finance_database: HEDP_DEV_RAW
  raw_finance_schema: FINANCE
  billing_as_of_date: '2025-01-01'
  governance_control_database: HEDP_DEV_GOVERNANCE
  governance_control_schema: CONTROL
  governance_data_quality_database: HEDP_DEV_GOVERNANCE
  governance_data_quality_schema: DATA_QUALITY
