{{ config(materialized='table', tags=['milestone_9', 'assurance', 'exception']) }}

select
    reconciliation_exception_key,
    reconciliation_control_key,
    exception_origin,
    exception_type,
    affected_object_type,
    affected_object_id,
    affected_object_key,
    source_record_id,
    governed_record_key,
    source_amount,
    governed_amount,
    signed_variance_amount,
    financial_value_at_risk,
    currency,
    rule_id,
    controlled_severity as severity,
    assigned_owner,
    assignment_reason,
    linked_exception_group_key,
    primary_exception_flag,
    include_in_value_at_risk,
    value_at_risk_method,
    value_at_risk_confidence,
    detected_at,
    target_resolution_days,
    target_resolution_date,
    overdue_flag,
    days_overdue,
    exception_age_days,
    root_cause,
    evidence_reference,
    source_relation,
    current_timestamp() as dbt_updated_at
from {{ ref('int_assurance__exception_priority') }}
