{{ config(materialized='table', tags=['milestone_8', 'billing', 'fact']) }}
select
    {{ generate_healthcare_surrogate_key(['invoice_line_id']) }} as invoice_line_key,
    {{ generate_healthcare_surrogate_key(['invoice_id']) }} as invoice_key,
    {{ generate_healthcare_surrogate_key(['billable_activity_id']) }} as billable_activity_key,
    {{ generate_healthcare_surrogate_key(['claim_line_id']) }} as claim_line_key,
    {{ generate_healthcare_surrogate_key(['service_id']) }} as service_key,
    {{ generate_healthcare_surrogate_key(['product_id']) }} as product_key,
    {{ generate_healthcare_surrogate_key(['coalesce(selected_tariff_id, tariff_id)']) }} as tariff_key,
    invoice_line_id,
    invoice_id,
    billable_activity_id,
    claim_line_id,
    service_id,
    product_id,
    tariff_id as source_tariff_id,
    selected_tariff_id as governed_tariff_id,
    description,
    quantity,
    unit_price as source_unit_price,
    governed_unit_price,
    source_net_amount,
    governed_net_amount,
    governed_tax_amount,
    source_gross_amount,
    governed_gross_amount,
    gross_variance_amount,
    gross_variance_status,
    tariff_match_status,
    tariff_selection_reason,
    source_record_id,
    source_relation,
    source_system,
    synthetic_flag,
    current_timestamp() as dbt_updated_at
from {{ ref('int_billing__invoice_line_calculations') }}
