{{ config(materialized='table', tags=['milestone_8', 'billing', 'fact']) }}
select
    {{ generate_healthcare_surrogate_key(['claim_line_id']) }} as claim_line_key,
    {{ generate_healthcare_surrogate_key(['claim_id']) }} as claim_key,
    {{ generate_healthcare_surrogate_key(['billable_activity_id']) }} as billable_activity_key,
    {{ generate_healthcare_surrogate_key(['service_id']) }} as service_key,
    {{ generate_healthcare_surrogate_key(['product_id']) }} as product_key,
    {{ generate_healthcare_surrogate_key(['coalesce(selected_tariff_id, tariff_id)']) }} as tariff_key,
    claim_line_id,
    claim_id,
    billable_activity_id,
    service_id,
    product_id,
    tariff_id as source_tariff_id,
    selected_tariff_id as governed_tariff_id,
    quantity,
    unit_price as source_unit_price,
    governed_unit_price,
    line_amount as source_line_amount,
    governed_line_amount,
    line_status,
    rejection_code,
    tariff_match_status,
    pricing_variance_amount,
    pricing_variance_status,
    source_record_id,
    source_relation,
    source_system,
    synthetic_flag,
    current_timestamp() as dbt_updated_at
from {{ ref('int_billing__claim_line_calculations') }}
