"""Versioned schema catalogue for every canonical synthetic dataset."""

from dataclasses import asdict, dataclass
from typing import Any

SCHEMA_VERSION = "1.0.0"


@dataclass(frozen=True)
class FieldSpec:
    name: str
    data_type: str
    nullable: bool
    description: str
    classification: str
    example: Any
    controlled_code_set: str | None = None


@dataclass(frozen=True)
class ForeignKey:
    fields: tuple[str, ...]
    reference_dataset: str
    reference_fields: tuple[str, ...]


@dataclass(frozen=True)
class DatasetSchema:
    name: str
    description: str
    fields: tuple[FieldSpec, ...]
    primary_key: tuple[str, ...]
    foreign_keys: tuple[ForeignKey, ...] = ()
    schema_version: str = SCHEMA_VERSION

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


def f(
    name: str,
    data_type: str,
    nullable: bool,
    description: str,
    classification: str,
    example: Any,
    code_set: str | None = None,
) -> FieldSpec:
    return FieldSpec(name, data_type, nullable, description, classification, example, code_set)


ID = "synthetic direct identifier"
QUASI = "synthetic quasi-identifier"
CLINICAL = "clinical"
OPERATIONAL = "operational"
RESEARCH = "research"
GOVERNANCE = "governance"
PUBLIC = "public metadata"

SCHEMAS: dict[str, DatasetSchema] = {
    "organisations": DatasetSchema(
        "organisations",
        "Synthetic healthcare organisations and hierarchy.",
        (
            f(
                "organisation_id",
                "string",
                False,
                "Stable synthetic organisation identifier.",
                ID,
                "ORG-000000001",
            ),
            f(
                "organisation_code",
                "string",
                False,
                "Synthetic business code.",
                PUBLIC,
                "SYN-ORG-001",
            ),
            f(
                "organisation_name",
                "string",
                False,
                "Obviously fictional label.",
                PUBLIC,
                "Synthetic Trust 001",
            ),
            f(
                "organisation_type",
                "string",
                False,
                "Portfolio organisation category.",
                OPERATIONAL,
                "TRUST",
                "organisation_type",
            ),
            f(
                "parent_organisation_id",
                "string",
                True,
                "Optional parent identifier.",
                OPERATIONAL,
                None,
            ),
            f("region", "string", False, "Synthetic broad region.", PUBLIC, "SYNTHETIC_NORTH"),
            f("active_flag", "boolean", False, "Whether the record is active.", OPERATIONAL, True),
            f("valid_from", "date", False, "Effective start date.", OPERATIONAL, "2015-01-01"),
            f("valid_to", "date", True, "Effective end date.", OPERATIONAL, None),
        ),
        ("organisation_id",),
        (ForeignKey(("parent_organisation_id",), "organisations", ("organisation_id",)),),
    ),
    "locations": DatasetSchema(
        "locations",
        "Synthetic healthcare delivery locations.",
        (
            f("location_id", "string", False, "Stable location identifier.", ID, "LOC-000000001"),
            f(
                "organisation_id",
                "string",
                False,
                "Owning organisation.",
                OPERATIONAL,
                "ORG-000000001",
            ),
            f("location_code", "string", False, "Synthetic location code.", PUBLIC, "SYN-LOC-001"),
            f(
                "location_name",
                "string",
                False,
                "Fictional location label.",
                PUBLIC,
                "Synthetic Clinic 001",
            ),
            f(
                "location_type",
                "string",
                False,
                "Portfolio location category.",
                OPERATIONAL,
                "CLINIC",
                "location_type",
            ),
            f(
                "specialty",
                "string",
                False,
                "Synthetic service specialty.",
                OPERATIONAL,
                "CARDIOLOGY",
                "specialty",
            ),
            f("active_flag", "boolean", False, "Whether location is active.", OPERATIONAL, True),
        ),
        ("location_id",),
        (ForeignKey(("organisation_id",), "organisations", ("organisation_id",)),),
    ),
    "providers": DatasetSchema(
        "providers",
        "Synthetic providers without personal names.",
        (
            f("provider_id", "string", False, "Stable provider identifier.", ID, "PRV-000000001"),
            f(
                "organisation_id",
                "string",
                False,
                "Employing organisation.",
                OPERATIONAL,
                "ORG-000000001",
            ),
            f(
                "provider_label",
                "string",
                False,
                "Obviously synthetic display label.",
                ID,
                "Provider-000001",
            ),
            f(
                "provider_role",
                "string",
                False,
                "Portfolio workforce role.",
                OPERATIONAL,
                "CONSULTANT",
                "provider_role",
            ),
            f(
                "specialty",
                "string",
                False,
                "Synthetic specialty.",
                OPERATIONAL,
                "GENERAL_MEDICINE",
                "specialty",
            ),
            f("active_flag", "boolean", False, "Whether provider is active.", OPERATIONAL, True),
            f("valid_from", "date", False, "Effective start date.", OPERATIONAL, "2018-01-01"),
            f("valid_to", "date", True, "Effective end date.", OPERATIONAL, None),
        ),
        ("provider_id",),
        (ForeignKey(("organisation_id",), "organisations", ("organisation_id",)),),
    ),
    "patients": DatasetSchema(
        "patients",
        "Synthetic pseudonymised patient records without names or contact details.",
        (
            f(
                "patient_id",
                "string",
                False,
                "Stable synthetic patient identifier.",
                ID,
                "PAT-000000001",
            ),
            f(
                "patient_pseudonym",
                "string",
                False,
                "Deterministic one-way synthetic pseudonym.",
                ID,
                "SYN-PSEUDO-ab12",
            ),
            f(
                "synthetic_nhs_number",
                "string",
                False,
                "Visibly synthetic non-production identifier.",
                ID,
                "SYN-NHS-000000001",
            ),
            f(
                "birth_date",
                "date",
                False,
                "Synthetic date of birth; sensitive if real.",
                QUASI,
                "1980-01-01",
            ),
            f("sex", "string", False, "Synthetic administrative sex code.", QUASI, "FEMALE", "sex"),
            f(
                "ethnicity",
                "string",
                False,
                "Synthetic broad ethnicity code.",
                QUASI,
                "NOT_STATED",
                "ethnicity",
            ),
            f(
                "postcode_sector",
                "string",
                False,
                "Non-real synthetic sector marker.",
                QUASI,
                "SYN-01",
            ),
            f(
                "registered_gp_organisation_id",
                "string",
                False,
                "Synthetic registered organisation.",
                OPERATIONAL,
                "ORG-000000001",
            ),
            f(
                "deceased_flag",
                "boolean",
                False,
                "Whether death_date is populated.",
                CLINICAL,
                False,
            ),
            f(
                "death_date",
                "date",
                True,
                "Synthetic date of death; sensitive if real.",
                CLINICAL,
                None,
            ),
            f(
                "record_created_at",
                "datetime",
                False,
                "Synthetic source creation time.",
                OPERATIONAL,
                "2023-01-01T00:00:00Z",
            ),
            f(
                "record_updated_at",
                "datetime",
                False,
                "Synthetic last update time.",
                OPERATIONAL,
                "2024-01-01T00:00:00Z",
            ),
        ),
        ("patient_id",),
        (ForeignKey(("registered_gp_organisation_id",), "organisations", ("organisation_id",)),),
    ),
    "encounters": DatasetSchema(
        "encounters",
        "Synthetic care encounters.",
        (
            f("encounter_id", "string", False, "Stable encounter identifier.", ID, "ENC-000000001"),
            f("patient_id", "string", False, "Encounter patient.", ID, "PAT-000000001"),
            f(
                "organisation_id",
                "string",
                False,
                "Delivering organisation.",
                OPERATIONAL,
                "ORG-000000001",
            ),
            f("location_id", "string", False, "Delivery location.", OPERATIONAL, "LOC-000000001"),
            f("provider_id", "string", False, "Responsible provider.", ID, "PRV-000000001"),
            f(
                "encounter_type",
                "string",
                False,
                "Encounter category.",
                CLINICAL,
                "OUTPATIENT",
                "encounter_type",
            ),
            f(
                "admission_method",
                "string",
                True,
                "Admission route for inpatient care.",
                CLINICAL,
                None,
            ),
            f(
                "start_datetime",
                "datetime",
                False,
                "Encounter start.",
                CLINICAL,
                "2024-01-01T09:00:00Z",
            ),
            f(
                "end_datetime",
                "datetime",
                True,
                "Encounter end; null when open.",
                CLINICAL,
                "2024-01-01T10:00:00Z",
            ),
            f(
                "status",
                "string",
                False,
                "Encounter status.",
                OPERATIONAL,
                "COMPLETED",
                "encounter_status",
            ),
            f(
                "discharge_destination",
                "string",
                True,
                "Synthetic discharge destination.",
                CLINICAL,
                None,
            ),
            f(
                "primary_diagnosis_code",
                "string",
                False,
                "Synthetic diagnosis code.",
                CLINICAL,
                "SYN-DX-01",
            ),
            f("source_system", "string", False, "Synthetic source label.", OPERATIONAL, "SYN-EPR"),
            f(
                "updated_at",
                "datetime",
                False,
                "Synthetic last update.",
                OPERATIONAL,
                "2024-01-01T10:05:00Z",
            ),
        ),
        ("encounter_id",),
        (
            ForeignKey(("patient_id",), "patients", ("patient_id",)),
            ForeignKey(("organisation_id",), "organisations", ("organisation_id",)),
            ForeignKey(("location_id",), "locations", ("location_id",)),
            ForeignKey(("provider_id",), "providers", ("provider_id",)),
        ),
    ),
    "admissions": DatasetSchema(
        "admissions",
        "Synthetic inpatient admission and discharge episodes.",
        (
            f("admission_id", "string", False, "Stable admission identifier.", ID, "ADM-000000001"),
            f("encounter_id", "string", False, "Related inpatient encounter.", ID, "ENC-000000001"),
            f("patient_id", "string", False, "Admitted patient.", ID, "PAT-000000001"),
            f(
                "admission_datetime",
                "datetime",
                False,
                "Admission time.",
                CLINICAL,
                "2024-01-01T09:00:00Z",
            ),
            f(
                "discharge_datetime",
                "datetime",
                True,
                "Discharge time; null when open.",
                CLINICAL,
                "2024-01-03T09:00:00Z",
            ),
            f(
                "admission_method",
                "string",
                False,
                "Synthetic admission route.",
                CLINICAL,
                "ELECTIVE",
            ),
            f(
                "discharge_method",
                "string",
                True,
                "Synthetic discharge outcome.",
                CLINICAL,
                "CLINICAL_DISCHARGE",
            ),
            f(
                "ward_id",
                "string",
                False,
                "Ward/location identifier.",
                OPERATIONAL,
                "LOC-000000001",
            ),
            f(
                "length_of_stay_days",
                "integer",
                True,
                "Calendar-day interval when discharged.",
                CLINICAL,
                2,
            ),
            f(
                "readmission_flag",
                "boolean",
                False,
                "Whether a prior eligible admission exists.",
                CLINICAL,
                False,
            ),
            f(
                "prior_admission_id",
                "string",
                True,
                "Prior admission supporting readmission flag.",
                CLINICAL,
                None,
            ),
            f(
                "updated_at",
                "datetime",
                False,
                "Synthetic last update.",
                OPERATIONAL,
                "2024-01-03T10:00:00Z",
            ),
        ),
        ("admission_id",),
        (
            ForeignKey(("encounter_id",), "encounters", ("encounter_id",)),
            ForeignKey(("patient_id",), "patients", ("patient_id",)),
            ForeignKey(("ward_id",), "locations", ("location_id",)),
            ForeignKey(("prior_admission_id",), "admissions", ("admission_id",)),
        ),
    ),
    "appointments": DatasetSchema(
        "appointments",
        "Synthetic outpatient appointments.",
        (
            f(
                "appointment_id",
                "string",
                False,
                "Stable appointment identifier.",
                ID,
                "APT-000000001",
            ),
            f("patient_id", "string", False, "Appointment patient.", ID, "PAT-000000001"),
            f(
                "organisation_id",
                "string",
                False,
                "Booking organisation.",
                OPERATIONAL,
                "ORG-000000001",
            ),
            f(
                "location_id",
                "string",
                False,
                "Appointment location.",
                OPERATIONAL,
                "LOC-000000001",
            ),
            f("provider_id", "string", False, "Appointment provider.", ID, "PRV-000000001"),
            f(
                "appointment_datetime",
                "datetime",
                False,
                "Scheduled time.",
                CLINICAL,
                "2025-01-10T09:00:00Z",
            ),
            f(
                "booking_datetime",
                "datetime",
                False,
                "Booking time.",
                OPERATIONAL,
                "2024-12-01T09:00:00Z",
            ),
            f(
                "appointment_type",
                "string",
                False,
                "Synthetic appointment category.",
                CLINICAL,
                "NEW",
            ),
            f(
                "attendance_status",
                "string",
                False,
                "Controlled attendance state.",
                OPERATIONAL,
                "ATTENDED",
                "attendance_status",
            ),
            f(
                "cancellation_reason",
                "string",
                True,
                "Required only for cancellation.",
                OPERATIONAL,
                None,
            ),
            f(
                "referral_id",
                "string",
                False,
                "Related referral clinical event.",
                CLINICAL,
                "CLE-000000001",
            ),
            f(
                "updated_at",
                "datetime",
                False,
                "Synthetic last update.",
                OPERATIONAL,
                "2025-01-10T10:00:00Z",
            ),
        ),
        ("appointment_id",),
        (
            ForeignKey(("patient_id",), "patients", ("patient_id",)),
            ForeignKey(("organisation_id",), "organisations", ("organisation_id",)),
            ForeignKey(("location_id",), "locations", ("location_id",)),
            ForeignKey(("provider_id",), "providers", ("provider_id",)),
            ForeignKey(("referral_id",), "clinical_events", ("clinical_event_id",)),
        ),
    ),
}

SCHEMAS.update(
    {
        "pathways": DatasetSchema(
            "pathways",
            "Synthetic referral-to-treatment pathways.",
            (
                f("pathway_id", "string", False, "Stable pathway identifier.", ID, "PTH-000000001"),
                f("patient_id", "string", False, "Pathway patient.", ID, "PAT-000000001"),
                f(
                    "referral_date",
                    "date",
                    False,
                    "Referral received date.",
                    CLINICAL,
                    "2024-01-01",
                ),
                f("pathway_type", "string", False, "Synthetic pathway category.", CLINICAL, "RTT"),
                f(
                    "specialty",
                    "string",
                    False,
                    "Pathway specialty.",
                    CLINICAL,
                    "CARDIOLOGY",
                    "specialty",
                ),
                f(
                    "organisation_id",
                    "string",
                    False,
                    "Responsible organisation.",
                    OPERATIONAL,
                    "ORG-000000001",
                ),
                f(
                    "clock_start_date",
                    "date",
                    False,
                    "Waiting-time clock start.",
                    CLINICAL,
                    "2024-01-01",
                ),
                f(
                    "current_status",
                    "string",
                    False,
                    "Current pathway status.",
                    OPERATIONAL,
                    "ACTIVE",
                    "pathway_status",
                ),
                f(
                    "current_stage",
                    "string",
                    False,
                    "Current pathway stage.",
                    OPERATIONAL,
                    "TRIAGED",
                    "pathway_stage",
                ),
                f(
                    "target_date",
                    "date",
                    False,
                    "Deterministic 126-day target.",
                    OPERATIONAL,
                    "2024-05-06",
                ),
                f("completion_date", "date", True, "Completion/cancellation date.", CLINICAL, None),
                f(
                    "waiting_days",
                    "integer",
                    False,
                    "Days from clock start to completion/reference date.",
                    OPERATIONAL,
                    45,
                ),
                f(
                    "breach_flag",
                    "boolean",
                    False,
                    "Whether waiting_days exceeds 126.",
                    GOVERNANCE,
                    False,
                ),
                f(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    OPERATIONAL,
                    "2024-02-15T00:00:00Z",
                ),
            ),
            ("pathway_id",),
            (
                ForeignKey(("patient_id",), "patients", ("patient_id",)),
                ForeignKey(("organisation_id",), "organisations", ("organisation_id",)),
            ),
        ),
        "clinical_events": DatasetSchema(
            "clinical_events",
            "Synthetic observations, diagnoses, procedures and referrals.",
            (
                f(
                    "clinical_event_id",
                    "string",
                    False,
                    "Stable clinical event identifier.",
                    ID,
                    "CLE-000000001",
                ),
                f("patient_id", "string", False, "Event patient.", ID, "PAT-000000001"),
                f("encounter_id", "string", False, "Related encounter.", ID, "ENC-000000001"),
                f("provider_id", "string", False, "Recording provider.", ID, "PRV-000000001"),
                f(
                    "event_type",
                    "string",
                    False,
                    "Controlled event category.",
                    CLINICAL,
                    "OBSERVATION",
                    "clinical_event_type",
                ),
                f("event_code", "string", False, "Synthetic event code.", CLINICAL, "SYN-OBS-01"),
                f(
                    "event_value",
                    "string",
                    True,
                    "Synthetic coded or numeric value.",
                    CLINICAL,
                    "72",
                ),
                f("event_unit", "string", True, "Synthetic unit when relevant.", CLINICAL, "bpm"),
                f(
                    "event_datetime",
                    "datetime",
                    False,
                    "Event time within encounter.",
                    CLINICAL,
                    "2024-01-01T09:30:00Z",
                ),
                f(
                    "source_system",
                    "string",
                    False,
                    "Synthetic source label.",
                    OPERATIONAL,
                    "SYN-EPR",
                ),
                f(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    OPERATIONAL,
                    "2024-01-01T10:00:00Z",
                ),
            ),
            ("clinical_event_id",),
            (
                ForeignKey(("patient_id",), "patients", ("patient_id",)),
                ForeignKey(("encounter_id",), "encounters", ("encounter_id",)),
                ForeignKey(("provider_id",), "providers", ("provider_id",)),
            ),
        ),
        "pathology_results": DatasetSchema(
            "pathology_results",
            "Synthetic laboratory results with derived abnormal flags.",
            (
                f(
                    "pathology_result_id",
                    "string",
                    False,
                    "Stable result identifier.",
                    ID,
                    "LAB-000000001",
                ),
                f("patient_id", "string", False, "Result patient.", ID, "PAT-000000001"),
                f("encounter_id", "string", False, "Related encounter.", ID, "ENC-000000001"),
                f(
                    "requesting_provider_id",
                    "string",
                    False,
                    "Requesting provider.",
                    ID,
                    "PRV-000000001",
                ),
                f(
                    "laboratory_organisation_id",
                    "string",
                    False,
                    "Processing laboratory.",
                    OPERATIONAL,
                    "ORG-000000005",
                ),
                f(
                    "test_code",
                    "string",
                    False,
                    "Controlled synthetic test code.",
                    CLINICAL,
                    "SYN-HB",
                ),
                f(
                    "test_name",
                    "string",
                    False,
                    "Synthetic test display name.",
                    CLINICAL,
                    "Synthetic haemoglobin",
                ),
                f("result_value", "number", False, "Synthetic numeric result.", CLINICAL, 140.0),
                f("result_unit", "string", False, "Result unit.", CLINICAL, "g/L"),
                f(
                    "reference_low",
                    "number",
                    False,
                    "Synthetic lower reference bound.",
                    CLINICAL,
                    120.0,
                ),
                f(
                    "reference_high",
                    "number",
                    False,
                    "Synthetic upper reference bound.",
                    CLINICAL,
                    170.0,
                ),
                f(
                    "abnormal_flag",
                    "boolean",
                    False,
                    "Derived outside-range indicator.",
                    CLINICAL,
                    False,
                ),
                f(
                    "specimen_datetime",
                    "datetime",
                    False,
                    "Specimen collection time.",
                    CLINICAL,
                    "2024-01-01T09:00:00Z",
                ),
                f(
                    "result_datetime",
                    "datetime",
                    False,
                    "Result availability time.",
                    CLINICAL,
                    "2024-01-01T14:00:00Z",
                ),
                f(
                    "status",
                    "string",
                    False,
                    "Controlled result status.",
                    OPERATIONAL,
                    "FINAL",
                    "pathology_status",
                ),
                f(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    OPERATIONAL,
                    "2024-01-01T14:05:00Z",
                ),
            ),
            ("pathology_result_id",),
            (
                ForeignKey(("patient_id",), "patients", ("patient_id",)),
                ForeignKey(("encounter_id",), "encounters", ("encounter_id",)),
                ForeignKey(("requesting_provider_id",), "providers", ("provider_id",)),
                ForeignKey(("laboratory_organisation_id",), "organisations", ("organisation_id",)),
            ),
        ),
        "medication_events": DatasetSchema(
            "medication_events",
            "Synthetic medication lifecycle events.",
            (
                f(
                    "medication_event_id",
                    "string",
                    False,
                    "Stable medication event identifier.",
                    ID,
                    "MED-000000001",
                ),
                f("patient_id", "string", False, "Medication patient.", ID, "PAT-000000001"),
                f("encounter_id", "string", False, "Related encounter.", ID, "ENC-000000001"),
                f("provider_id", "string", False, "Responsible provider.", ID, "PRV-000000001"),
                f(
                    "medication_code",
                    "string",
                    False,
                    "Synthetic medication code.",
                    CLINICAL,
                    "SYN-MED-01",
                ),
                f(
                    "medication_name",
                    "string",
                    False,
                    "Fictional medication label.",
                    CLINICAL,
                    "Synthetic Medicine 01",
                ),
                f(
                    "event_type",
                    "string",
                    False,
                    "Medication lifecycle event.",
                    CLINICAL,
                    "PRESCRIPTION",
                    "medication_event_type",
                ),
                f("dose", "number", False, "Synthetic dose amount.", CLINICAL, 5.0),
                f("dose_unit", "string", False, "Dose unit.", CLINICAL, "mg"),
                f("route", "string", False, "Administration route.", CLINICAL, "ORAL"),
                f(
                    "event_datetime",
                    "datetime",
                    False,
                    "Medication event time.",
                    CLINICAL,
                    "2024-01-01T10:00:00Z",
                ),
                f("status", "string", False, "Synthetic event status.", OPERATIONAL, "COMPLETED"),
                f(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    OPERATIONAL,
                    "2024-01-01T10:05:00Z",
                ),
            ),
            ("medication_event_id",),
            (
                ForeignKey(("patient_id",), "patients", ("patient_id",)),
                ForeignKey(("encounter_id",), "encounters", ("encounter_id",)),
                ForeignKey(("provider_id",), "providers", ("provider_id",)),
            ),
        ),
        "research_consent": DatasetSchema(
            "research_consent",
            "Synthetic research consent status.",
            (
                f("consent_id", "string", False, "Stable consent identifier.", ID, "CON-000000001"),
                f("patient_id", "string", False, "Consent patient.", ID, "PAT-000000001"),
                f(
                    "consent_type",
                    "string",
                    False,
                    "Synthetic consent purpose.",
                    RESEARCH,
                    "GENERAL_RESEARCH",
                ),
                f(
                    "consent_status",
                    "string",
                    False,
                    "Controlled consent state.",
                    RESEARCH,
                    "ACTIVE",
                    "consent_status",
                ),
                f("valid_from", "date", False, "Consent validity start.", RESEARCH, "2023-01-01"),
                f("valid_to", "date", True, "Consent expiry date.", RESEARCH, None),
                f(
                    "withdrawal_date",
                    "date",
                    True,
                    "Withdrawal date when withdrawn.",
                    RESEARCH,
                    None,
                ),
                f(
                    "research_use_allowed",
                    "boolean",
                    False,
                    "Derived active validity indicator.",
                    GOVERNANCE,
                    True,
                ),
                f(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    OPERATIONAL,
                    "2024-01-01T00:00:00Z",
                ),
            ),
            ("consent_id",),
            (ForeignKey(("patient_id",), "patients", ("patient_id",)),),
        ),
        "research_cohorts": DatasetSchema(
            "research_cohorts",
            "Synthetic approved cohort membership.",
            (
                f(
                    "cohort_membership_id",
                    "string",
                    False,
                    "Stable membership identifier.",
                    ID,
                    "COH-000000001",
                ),
                f(
                    "cohort_id",
                    "string",
                    False,
                    "Synthetic cohort identifier.",
                    RESEARCH,
                    "SYN-COHORT-01",
                ),
                f(
                    "patient_id",
                    "string",
                    False,
                    "Eligible synthetic patient.",
                    ID,
                    "PAT-000000001",
                ),
                f(
                    "cohort_name",
                    "string",
                    False,
                    "Fictional cohort label.",
                    RESEARCH,
                    "Synthetic Cardiology Study",
                ),
                f(
                    "inclusion_date",
                    "date",
                    False,
                    "Membership start date.",
                    RESEARCH,
                    "2024-01-01",
                ),
                f("exclusion_date", "date", True, "Membership exclusion date.", RESEARCH, None),
                f(
                    "inclusion_reason",
                    "string",
                    False,
                    "Controlled inclusion rationale.",
                    RESEARCH,
                    "VALID_ACTIVE_CONSENT",
                ),
                f(
                    "eligible_flag",
                    "boolean",
                    False,
                    "Derived eligibility at inclusion.",
                    GOVERNANCE,
                    True,
                ),
                f(
                    "consent_status_at_inclusion",
                    "string",
                    False,
                    "Consent state at inclusion.",
                    GOVERNANCE,
                    "ACTIVE",
                    "consent_status",
                ),
            ),
            ("cohort_membership_id",),
            (ForeignKey(("patient_id",), "patients", ("patient_id",)),),
        ),
        "audit_events": DatasetSchema(
            "audit_events",
            "Synthetic platform audit activity.",
            (
                f(
                    "audit_event_id",
                    "string",
                    False,
                    "Stable audit event identifier.",
                    ID,
                    "AUD-000000001",
                ),
                f(
                    "actor_id",
                    "string",
                    False,
                    "Synthetic user/service actor.",
                    ID,
                    "SVC-SYNTHETIC-01",
                ),
                f(
                    "actor_role",
                    "string",
                    False,
                    "Synthetic platform role.",
                    GOVERNANCE,
                    "DATA_ENGINEER",
                ),
                f(
                    "action",
                    "string",
                    False,
                    "Controlled audit action.",
                    GOVERNANCE,
                    "READ",
                    "audit_action",
                ),
                f(
                    "object_type",
                    "string",
                    False,
                    "Audited object category.",
                    GOVERNANCE,
                    "DATASET",
                ),
                f(
                    "object_id",
                    "string",
                    False,
                    "Synthetic object reference.",
                    GOVERNANCE,
                    "patients",
                ),
                f(
                    "event_datetime",
                    "datetime",
                    False,
                    "Audit event time.",
                    GOVERNANCE,
                    "2024-01-01T00:00:00Z",
                ),
                f("outcome", "string", False, "Synthetic outcome.", GOVERNANCE, "SUCCESS"),
                f(
                    "source_component",
                    "string",
                    False,
                    "Synthetic component label.",
                    GOVERNANCE,
                    "GENERATOR",
                ),
                f(
                    "environment",
                    "string",
                    False,
                    "Non-secret environment label.",
                    GOVERNANCE,
                    "local",
                ),
                f(
                    "correlation_id",
                    "string",
                    False,
                    "Stable synthetic correlation identifier.",
                    GOVERNANCE,
                    "COR-000000001",
                ),
            ),
            ("audit_event_id",),
        ),
        "data_quality_events": DatasetSchema(
            "data_quality_events",
            "Deterministic register of intentionally injected defects.",
            (
                f(
                    "quality_event_id",
                    "string",
                    False,
                    "Stable quality event identifier.",
                    ID,
                    "DQE-000000001",
                ),
                f(
                    "dataset_name",
                    "string",
                    False,
                    "Affected canonical dataset.",
                    GOVERNANCE,
                    "appointments",
                ),
                f(
                    "rule_id",
                    "string",
                    False,
                    "Stable validation rule identifier.",
                    GOVERNANCE,
                    "BR-APT-001",
                ),
                f(
                    "rule_name",
                    "string",
                    False,
                    "Human-readable rule.",
                    GOVERNANCE,
                    "Cancelled appointment reason required",
                ),
                f(
                    "severity",
                    "string",
                    False,
                    "Controlled quality severity.",
                    GOVERNANCE,
                    "ERROR",
                    "quality_severity",
                ),
                f(
                    "record_identifier",
                    "string",
                    False,
                    "Affected synthetic record identifier.",
                    GOVERNANCE,
                    "APT-000000001",
                ),
                f(
                    "detected_at",
                    "datetime",
                    False,
                    "Deterministic detection timestamp.",
                    GOVERNANCE,
                    "2025-01-01T00:00:00Z",
                ),
                f("status", "string", False, "Quality workflow state.", GOVERNANCE, "OPEN"),
                f(
                    "resolution_action",
                    "string",
                    False,
                    "Expected remediation or test intent.",
                    GOVERNANCE,
                    "NEGATIVE_TEST_ONLY",
                ),
            ),
            ("quality_event_id",),
        ),
    }
)

DATASET_ORDER = tuple(SCHEMAS)
