"""Versioned schema catalogue for every canonical synthetic dataset."""

from dataclasses import asdict, dataclass
from typing import Any

SCHEMA_VERSION = "1.0.0"


@dataclass(frozen=True)
class FieldSpec:
    name: str
    data_type: str
    nullable: bool
    description: str
    classification: str
    example: Any
    controlled_code_set: str | None = None


@dataclass(frozen=True)
class ForeignKey:
    fields: tuple[str, ...]
    reference_dataset: str
    reference_fields: tuple[str, ...]


@dataclass(frozen=True)
class DatasetSchema:
    name: str
    description: str
    fields: tuple[FieldSpec, ...]
    primary_key: tuple[str, ...]
    foreign_keys: tuple[ForeignKey, ...] = ()
    schema_version: str = SCHEMA_VERSION

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


def f(
    name: str,
    data_type: str,
    nullable: bool,
    description: str,
    classification: str,
    example: Any,
    code_set: str | None = None,
) -> FieldSpec:
    return FieldSpec(name, data_type, nullable, description, classification, example, code_set)


ID = "synthetic direct identifier"
QUASI = "synthetic quasi-identifier"
CLINICAL = "clinical"
OPERATIONAL = "operational"
RESEARCH = "research"
GOVERNANCE = "governance"
PUBLIC = "public metadata"
FINANCIAL = "financial confidential"

SCHEMAS: dict[str, DatasetSchema] = {
    "organisations": DatasetSchema(
        "organisations",
        "Synthetic healthcare organisations and hierarchy.",
        (
            f(
                "organisation_id",
                "string",
                False,
                "Stable synthetic organisation identifier.",
                ID,
                "ORG-000000001",
            ),
            f(
                "organisation_code",
                "string",
                False,
                "Synthetic business code.",
                PUBLIC,
                "SYN-ORG-001",
            ),
            f(
                "organisation_name",
                "string",
                False,
                "Obviously fictional label.",
                PUBLIC,
                "Synthetic Trust 001",
            ),
            f(
                "organisation_type",
                "string",
                False,
                "Portfolio organisation category.",
                OPERATIONAL,
                "TRUST",
                "organisation_type",
            ),
            f(
                "parent_organisation_id",
                "string",
                True,
                "Optional parent identifier.",
                OPERATIONAL,
                None,
            ),
            f("region", "string", False, "Synthetic broad region.", PUBLIC, "SYNTHETIC_NORTH"),
            f("active_flag", "boolean", False, "Whether the record is active.", OPERATIONAL, True),
            f("valid_from", "date", False, "Effective start date.", OPERATIONAL, "2015-01-01"),
            f("valid_to", "date", True, "Effective end date.", OPERATIONAL, None),
        ),
        ("organisation_id",),
        (ForeignKey(("parent_organisation_id",), "organisations", ("organisation_id",)),),
    ),
    "locations": DatasetSchema(
        "locations",
        "Synthetic healthcare delivery locations.",
        (
            f("location_id", "string", False, "Stable location identifier.", ID, "LOC-000000001"),
            f(
                "organisation_id",
                "string",
                False,
                "Owning organisation.",
                OPERATIONAL,
                "ORG-000000001",
            ),
            f("location_code", "string", False, "Synthetic location code.", PUBLIC, "SYN-LOC-001"),
            f(
                "location_name",
                "string",
                False,
                "Fictional location label.",
                PUBLIC,
                "Synthetic Clinic 001",
            ),
            f(
                "location_type",
                "string",
                False,
                "Portfolio location category.",
                OPERATIONAL,
                "CLINIC",
                "location_type",
            ),
            f(
                "specialty",
                "string",
                False,
                "Synthetic service specialty.",
                OPERATIONAL,
                "CARDIOLOGY",
                "specialty",
            ),
            f("active_flag", "boolean", False, "Whether location is active.", OPERATIONAL, True),
        ),
        ("location_id",),
        (ForeignKey(("organisation_id",), "organisations", ("organisation_id",)),),
    ),
    "providers": DatasetSchema(
        "providers",
        "Synthetic providers without personal names.",
        (
            f("provider_id", "string", False, "Stable provider identifier.", ID, "PRV-000000001"),
            f(
                "organisation_id",
                "string",
                False,
                "Employing organisation.",
                OPERATIONAL,
                "ORG-000000001",
            ),
            f(
                "provider_label",
                "string",
                False,
                "Obviously synthetic display label.",
                ID,
                "Provider-000001",
            ),
            f(
                "provider_role",
                "string",
                False,
                "Portfolio workforce role.",
                OPERATIONAL,
                "CONSULTANT",
                "provider_role",
            ),
            f(
                "specialty",
                "string",
                False,
                "Synthetic specialty.",
                OPERATIONAL,
                "GENERAL_MEDICINE",
                "specialty",
            ),
            f("active_flag", "boolean", False, "Whether provider is active.", OPERATIONAL, True),
            f("valid_from", "date", False, "Effective start date.", OPERATIONAL, "2018-01-01"),
            f("valid_to", "date", True, "Effective end date.", OPERATIONAL, None),
        ),
        ("provider_id",),
        (ForeignKey(("organisation_id",), "organisations", ("organisation_id",)),),
    ),
    "patients": DatasetSchema(
        "patients",
        "Synthetic pseudonymised patient records without names or contact details.",
        (
            f(
                "patient_id",
                "string",
                False,
                "Stable synthetic patient identifier.",
                ID,
                "PAT-000000001",
            ),
            f(
                "patient_pseudonym",
                "string",
                False,
                "Deterministic one-way synthetic pseudonym.",
                ID,
                "SYN-PSEUDO-ab12",
            ),
            f(
                "synthetic_nhs_number",
                "string",
                False,
                "Visibly synthetic non-production identifier.",
                ID,
                "SYN-NHS-000000001",
            ),
            f(
                "birth_date",
                "date",
                False,
                "Synthetic date of birth; sensitive if real.",
                QUASI,
                "1980-01-01",
            ),
            f("sex", "string", False, "Synthetic administrative sex code.", QUASI, "FEMALE", "sex"),
            f(
                "ethnicity",
                "string",
                False,
                "Synthetic broad ethnicity code.",
                QUASI,
                "NOT_STATED",
                "ethnicity",
            ),
            f(
                "postcode_sector",
                "string",
                False,
                "Non-real synthetic sector marker.",
                QUASI,
                "SYN-01",
            ),
            f(
                "registered_gp_organisation_id",
                "string",
                False,
                "Synthetic registered organisation.",
                OPERATIONAL,
                "ORG-000000001",
            ),
            f(
                "deceased_flag",
                "boolean",
                False,
                "Whether death_date is populated.",
                CLINICAL,
                False,
            ),
            f(
                "death_date",
                "date",
                True,
                "Synthetic date of death; sensitive if real.",
                CLINICAL,
                None,
            ),
            f(
                "record_created_at",
                "datetime",
                False,
                "Synthetic source creation time.",
                OPERATIONAL,
                "2023-01-01T00:00:00Z",
            ),
            f(
                "record_updated_at",
                "datetime",
                False,
                "Synthetic last update time.",
                OPERATIONAL,
                "2024-01-01T00:00:00Z",
            ),
        ),
        ("patient_id",),
        (ForeignKey(("registered_gp_organisation_id",), "organisations", ("organisation_id",)),),
    ),
    "encounters": DatasetSchema(
        "encounters",
        "Synthetic care encounters.",
        (
            f("encounter_id", "string", False, "Stable encounter identifier.", ID, "ENC-000000001"),
            f("patient_id", "string", False, "Encounter patient.", ID, "PAT-000000001"),
            f(
                "organisation_id",
                "string",
                False,
                "Delivering organisation.",
                OPERATIONAL,
                "ORG-000000001",
            ),
            f("location_id", "string", False, "Delivery location.", OPERATIONAL, "LOC-000000001"),
            f("provider_id", "string", False, "Responsible provider.", ID, "PRV-000000001"),
            f(
                "encounter_type",
                "string",
                False,
                "Encounter category.",
                CLINICAL,
                "OUTPATIENT",
                "encounter_type",
            ),
            f(
                "admission_method",
                "string",
                True,
                "Admission route for inpatient care.",
                CLINICAL,
                None,
            ),
            f(
                "start_datetime",
                "datetime",
                False,
                "Encounter start.",
                CLINICAL,
                "2024-01-01T09:00:00Z",
            ),
            f(
                "end_datetime",
                "datetime",
                True,
                "Encounter end; null when open.",
                CLINICAL,
                "2024-01-01T10:00:00Z",
            ),
            f(
                "status",
                "string",
                False,
                "Encounter status.",
                OPERATIONAL,
                "COMPLETED",
                "encounter_status",
            ),
            f(
                "discharge_destination",
                "string",
                True,
                "Synthetic discharge destination.",
                CLINICAL,
                None,
            ),
            f(
                "primary_diagnosis_code",
                "string",
                False,
                "Synthetic diagnosis code.",
                CLINICAL,
                "SYN-DX-01",
            ),
            f("source_system", "string", False, "Synthetic source label.", OPERATIONAL, "SYN-EPR"),
            f(
                "updated_at",
                "datetime",
                False,
                "Synthetic last update.",
                OPERATIONAL,
                "2024-01-01T10:05:00Z",
            ),
        ),
        ("encounter_id",),
        (
            ForeignKey(("patient_id",), "patients", ("patient_id",)),
            ForeignKey(("organisation_id",), "organisations", ("organisation_id",)),
            ForeignKey(("location_id",), "locations", ("location_id",)),
            ForeignKey(("provider_id",), "providers", ("provider_id",)),
        ),
    ),
    "admissions": DatasetSchema(
        "admissions",
        "Synthetic inpatient admission and discharge episodes.",
        (
            f("admission_id", "string", False, "Stable admission identifier.", ID, "ADM-000000001"),
            f("encounter_id", "string", False, "Related inpatient encounter.", ID, "ENC-000000001"),
            f("patient_id", "string", False, "Admitted patient.", ID, "PAT-000000001"),
            f(
                "admission_datetime",
                "datetime",
                False,
                "Admission time.",
                CLINICAL,
                "2024-01-01T09:00:00Z",
            ),
            f(
                "discharge_datetime",
                "datetime",
                True,
                "Discharge time; null when open.",
                CLINICAL,
                "2024-01-03T09:00:00Z",
            ),
            f(
                "admission_method",
                "string",
                False,
                "Synthetic admission route.",
                CLINICAL,
                "ELECTIVE",
            ),
            f(
                "discharge_method",
                "string",
                True,
                "Synthetic discharge outcome.",
                CLINICAL,
                "CLINICAL_DISCHARGE",
            ),
            f(
                "ward_id",
                "string",
                False,
                "Ward/location identifier.",
                OPERATIONAL,
                "LOC-000000001",
            ),
            f(
                "length_of_stay_days",
                "integer",
                True,
                "Calendar-day interval when discharged.",
                CLINICAL,
                2,
            ),
            f(
                "readmission_flag",
                "boolean",
                False,
                "Whether a prior eligible admission exists.",
                CLINICAL,
                False,
            ),
            f(
                "prior_admission_id",
                "string",
                True,
                "Prior admission supporting readmission flag.",
                CLINICAL,
                None,
            ),
            f(
                "updated_at",
                "datetime",
                False,
                "Synthetic last update.",
                OPERATIONAL,
                "2024-01-03T10:00:00Z",
            ),
        ),
        ("admission_id",),
        (
            ForeignKey(("encounter_id",), "encounters", ("encounter_id",)),
            ForeignKey(("patient_id",), "patients", ("patient_id",)),
            ForeignKey(("ward_id",), "locations", ("location_id",)),
            ForeignKey(("prior_admission_id",), "admissions", ("admission_id",)),
        ),
    ),
    "appointments": DatasetSchema(
        "appointments",
        "Synthetic outpatient appointments.",
        (
            f(
                "appointment_id",
                "string",
                False,
                "Stable appointment identifier.",
                ID,
                "APT-000000001",
            ),
            f("patient_id", "string", False, "Appointment patient.", ID, "PAT-000000001"),
            f(
                "organisation_id",
                "string",
                False,
                "Booking organisation.",
                OPERATIONAL,
                "ORG-000000001",
            ),
            f(
                "location_id",
                "string",
                False,
                "Appointment location.",
                OPERATIONAL,
                "LOC-000000001",
            ),
            f("provider_id", "string", False, "Appointment provider.", ID, "PRV-000000001"),
            f(
                "appointment_datetime",
                "datetime",
                False,
                "Scheduled time.",
                CLINICAL,
                "2025-01-10T09:00:00Z",
            ),
            f(
                "booking_datetime",
                "datetime",
                False,
                "Booking time.",
                OPERATIONAL,
                "2024-12-01T09:00:00Z",
            ),
            f(
                "appointment_type",
                "string",
                False,
                "Synthetic appointment category.",
                CLINICAL,
                "NEW",
            ),
            f(
                "attendance_status",
                "string",
                False,
                "Controlled attendance state.",
                OPERATIONAL,
                "ATTENDED",
                "attendance_status",
            ),
            f(
                "cancellation_reason",
                "string",
                True,
                "Required only for cancellation.",
                OPERATIONAL,
                None,
            ),
            f(
                "referral_id",
                "string",
                False,
                "Related referral clinical event.",
                CLINICAL,
                "CLE-000000001",
            ),
            f(
                "updated_at",
                "datetime",
                False,
                "Synthetic last update.",
                OPERATIONAL,
                "2025-01-10T10:00:00Z",
            ),
        ),
        ("appointment_id",),
        (
            ForeignKey(("patient_id",), "patients", ("patient_id",)),
            ForeignKey(("organisation_id",), "organisations", ("organisation_id",)),
            ForeignKey(("location_id",), "locations", ("location_id",)),
            ForeignKey(("provider_id",), "providers", ("provider_id",)),
            ForeignKey(("referral_id",), "clinical_events", ("clinical_event_id",)),
        ),
    ),
}

SCHEMAS.update(
    {
        "pathways": DatasetSchema(
            "pathways",
            "Synthetic referral-to-treatment pathways.",
            (
                f("pathway_id", "string", False, "Stable pathway identifier.", ID, "PTH-000000001"),
                f("patient_id", "string", False, "Pathway patient.", ID, "PAT-000000001"),
                f(
                    "referral_date",
                    "date",
                    False,
                    "Referral received date.",
                    CLINICAL,
                    "2024-01-01",
                ),
                f("pathway_type", "string", False, "Synthetic pathway category.", CLINICAL, "RTT"),
                f(
                    "specialty",
                    "string",
                    False,
                    "Pathway specialty.",
                    CLINICAL,
                    "CARDIOLOGY",
                    "specialty",
                ),
                f(
                    "organisation_id",
                    "string",
                    False,
                    "Responsible organisation.",
                    OPERATIONAL,
                    "ORG-000000001",
                ),
                f(
                    "clock_start_date",
                    "date",
                    False,
                    "Waiting-time clock start.",
                    CLINICAL,
                    "2024-01-01",
                ),
                f(
                    "current_status",
                    "string",
                    False,
                    "Current pathway status.",
                    OPERATIONAL,
                    "ACTIVE",
                    "pathway_status",
                ),
                f(
                    "current_stage",
                    "string",
                    False,
                    "Current pathway stage.",
                    OPERATIONAL,
                    "TRIAGED",
                    "pathway_stage",
                ),
                f(
                    "target_date",
                    "date",
                    False,
                    "Deterministic 126-day target.",
                    OPERATIONAL,
                    "2024-05-06",
                ),
                f("completion_date", "date", True, "Completion/cancellation date.", CLINICAL, None),
                f(
                    "waiting_days",
                    "integer",
                    False,
                    "Days from clock start to completion/reference date.",
                    OPERATIONAL,
                    45,
                ),
                f(
                    "breach_flag",
                    "boolean",
                    False,
                    "Whether waiting_days exceeds 126.",
                    GOVERNANCE,
                    False,
                ),
                f(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    OPERATIONAL,
                    "2024-02-15T00:00:00Z",
                ),
            ),
            ("pathway_id",),
            (
                ForeignKey(("patient_id",), "patients", ("patient_id",)),
                ForeignKey(("organisation_id",), "organisations", ("organisation_id",)),
            ),
        ),
        "clinical_events": DatasetSchema(
            "clinical_events",
            "Synthetic observations, diagnoses, procedures and referrals.",
            (
                f(
                    "clinical_event_id",
                    "string",
                    False,
                    "Stable clinical event identifier.",
                    ID,
                    "CLE-000000001",
                ),
                f("patient_id", "string", False, "Event patient.", ID, "PAT-000000001"),
                f("encounter_id", "string", False, "Related encounter.", ID, "ENC-000000001"),
                f("provider_id", "string", False, "Recording provider.", ID, "PRV-000000001"),
                f(
                    "event_type",
                    "string",
                    False,
                    "Controlled event category.",
                    CLINICAL,
                    "OBSERVATION",
                    "clinical_event_type",
                ),
                f("event_code", "string", False, "Synthetic event code.", CLINICAL, "SYN-OBS-01"),
                f(
                    "event_value",
                    "string",
                    True,
                    "Synthetic coded or numeric value.",
                    CLINICAL,
                    "72",
                ),
                f("event_unit", "string", True, "Synthetic unit when relevant.", CLINICAL, "bpm"),
                f(
                    "event_datetime",
                    "datetime",
                    False,
                    "Event time within encounter.",
                    CLINICAL,
                    "2024-01-01T09:30:00Z",
                ),
                f(
                    "source_system",
                    "string",
                    False,
                    "Synthetic source label.",
                    OPERATIONAL,
                    "SYN-EPR",
                ),
                f(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    OPERATIONAL,
                    "2024-01-01T10:00:00Z",
                ),
            ),
            ("clinical_event_id",),
            (
                ForeignKey(("patient_id",), "patients", ("patient_id",)),
                ForeignKey(("encounter_id",), "encounters", ("encounter_id",)),
                ForeignKey(("provider_id",), "providers", ("provider_id",)),
            ),
        ),
        "pathology_results": DatasetSchema(
            "pathology_results",
            "Synthetic laboratory results with derived abnormal flags.",
            (
                f(
                    "pathology_result_id",
                    "string",
                    False,
                    "Stable result identifier.",
                    ID,
                    "LAB-000000001",
                ),
                f("patient_id", "string", False, "Result patient.", ID, "PAT-000000001"),
                f("encounter_id", "string", False, "Related encounter.", ID, "ENC-000000001"),
                f(
                    "requesting_provider_id",
                    "string",
                    False,
                    "Requesting provider.",
                    ID,
                    "PRV-000000001",
                ),
                f(
                    "laboratory_organisation_id",
                    "string",
                    False,
                    "Processing laboratory.",
                    OPERATIONAL,
                    "ORG-000000005",
                ),
                f(
                    "test_code",
                    "string",
                    False,
                    "Controlled synthetic test code.",
                    CLINICAL,
                    "SYN-HB",
                ),
                f(
                    "test_name",
                    "string",
                    False,
                    "Synthetic test display name.",
                    CLINICAL,
                    "Synthetic haemoglobin",
                ),
                f("result_value", "number", False, "Synthetic numeric result.", CLINICAL, 140.0),
                f("result_unit", "string", False, "Result unit.", CLINICAL, "g/L"),
                f(
                    "reference_low",
                    "number",
                    False,
                    "Synthetic lower reference bound.",
                    CLINICAL,
                    120.0,
                ),
                f(
                    "reference_high",
                    "number",
                    False,
                    "Synthetic upper reference bound.",
                    CLINICAL,
                    170.0,
                ),
                f(
                    "abnormal_flag",
                    "boolean",
                    False,
                    "Derived outside-range indicator.",
                    CLINICAL,
                    False,
                ),
                f(
                    "specimen_datetime",
                    "datetime",
                    False,
                    "Specimen collection time.",
                    CLINICAL,
                    "2024-01-01T09:00:00Z",
                ),
                f(
                    "result_datetime",
                    "datetime",
                    False,
                    "Result availability time.",
                    CLINICAL,
                    "2024-01-01T14:00:00Z",
                ),
                f(
                    "status",
                    "string",
                    False,
                    "Controlled result status.",
                    OPERATIONAL,
                    "FINAL",
                    "pathology_status",
                ),
                f(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    OPERATIONAL,
                    "2024-01-01T14:05:00Z",
                ),
            ),
            ("pathology_result_id",),
            (
                ForeignKey(("patient_id",), "patients", ("patient_id",)),
                ForeignKey(("encounter_id",), "encounters", ("encounter_id",)),
                ForeignKey(("requesting_provider_id",), "providers", ("provider_id",)),
                ForeignKey(("laboratory_organisation_id",), "organisations", ("organisation_id",)),
            ),
        ),
        "medication_events": DatasetSchema(
            "medication_events",
            "Synthetic medication lifecycle events.",
            (
                f(
                    "medication_event_id",
                    "string",
                    False,
                    "Stable medication event identifier.",
                    ID,
                    "MED-000000001",
                ),
                f("patient_id", "string", False, "Medication patient.", ID, "PAT-000000001"),
                f("encounter_id", "string", False, "Related encounter.", ID, "ENC-000000001"),
                f("provider_id", "string", False, "Responsible provider.", ID, "PRV-000000001"),
                f(
                    "medication_code",
                    "string",
                    False,
                    "Synthetic medication code.",
                    CLINICAL,
                    "SYN-MED-01",
                ),
                f(
                    "medication_name",
                    "string",
                    False,
                    "Fictional medication label.",
                    CLINICAL,
                    "Synthetic Medicine 01",
                ),
                f(
                    "event_type",
                    "string",
                    False,
                    "Medication lifecycle event.",
                    CLINICAL,
                    "PRESCRIPTION",
                    "medication_event_type",
                ),
                f("dose", "number", False, "Synthetic dose amount.", CLINICAL, 5.0),
                f("dose_unit", "string", False, "Dose unit.", CLINICAL, "mg"),
                f("route", "string", False, "Administration route.", CLINICAL, "ORAL"),
                f(
                    "event_datetime",
                    "datetime",
                    False,
                    "Medication event time.",
                    CLINICAL,
                    "2024-01-01T10:00:00Z",
                ),
                f("status", "string", False, "Synthetic event status.", OPERATIONAL, "COMPLETED"),
                f(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    OPERATIONAL,
                    "2024-01-01T10:05:00Z",
                ),
            ),
            ("medication_event_id",),
            (
                ForeignKey(("patient_id",), "patients", ("patient_id",)),
                ForeignKey(("encounter_id",), "encounters", ("encounter_id",)),
                ForeignKey(("provider_id",), "providers", ("provider_id",)),
            ),
        ),
        "research_consent": DatasetSchema(
            "research_consent",
            "Synthetic research consent status.",
            (
                f("consent_id", "string", False, "Stable consent identifier.", ID, "CON-000000001"),
                f("patient_id", "string", False, "Consent patient.", ID, "PAT-000000001"),
                f(
                    "consent_type",
                    "string",
                    False,
                    "Synthetic consent purpose.",
                    RESEARCH,
                    "GENERAL_RESEARCH",
                ),
                f(
                    "consent_status",
                    "string",
                    False,
                    "Controlled consent state.",
                    RESEARCH,
                    "ACTIVE",
                    "consent_status",
                ),
                f("valid_from", "date", False, "Consent validity start.", RESEARCH, "2023-01-01"),
                f("valid_to", "date", True, "Consent expiry date.", RESEARCH, None),
                f(
                    "withdrawal_date",
                    "date",
                    True,
                    "Withdrawal date when withdrawn.",
                    RESEARCH,
                    None,
                ),
                f(
                    "research_use_allowed",
                    "boolean",
                    False,
                    "Derived active validity indicator.",
                    GOVERNANCE,
                    True,
                ),
                f(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    OPERATIONAL,
                    "2024-01-01T00:00:00Z",
                ),
            ),
            ("consent_id",),
            (ForeignKey(("patient_id",), "patients", ("patient_id",)),),
        ),
        "research_cohorts": DatasetSchema(
            "research_cohorts",
            "Synthetic approved cohort membership.",
            (
                f(
                    "cohort_membership_id",
                    "string",
                    False,
                    "Stable membership identifier.",
                    ID,
                    "COH-000000001",
                ),
                f(
                    "cohort_id",
                    "string",
                    False,
                    "Synthetic cohort identifier.",
                    RESEARCH,
                    "SYN-COHORT-01",
                ),
                f(
                    "patient_id",
                    "string",
                    False,
                    "Eligible synthetic patient.",
                    ID,
                    "PAT-000000001",
                ),
                f(
                    "cohort_name",
                    "string",
                    False,
                    "Fictional cohort label.",
                    RESEARCH,
                    "Synthetic Cardiology Study",
                ),
                f(
                    "inclusion_date",
                    "date",
                    False,
                    "Membership start date.",
                    RESEARCH,
                    "2024-01-01",
                ),
                f("exclusion_date", "date", True, "Membership exclusion date.", RESEARCH, None),
                f(
                    "inclusion_reason",
                    "string",
                    False,
                    "Controlled inclusion rationale.",
                    RESEARCH,
                    "VALID_ACTIVE_CONSENT",
                ),
                f(
                    "eligible_flag",
                    "boolean",
                    False,
                    "Derived eligibility at inclusion.",
                    GOVERNANCE,
                    True,
                ),
                f(
                    "consent_status_at_inclusion",
                    "string",
                    False,
                    "Consent state at inclusion.",
                    GOVERNANCE,
                    "ACTIVE",
                    "consent_status",
                ),
            ),
            ("cohort_membership_id",),
            (ForeignKey(("patient_id",), "patients", ("patient_id",)),),
        ),
        "audit_events": DatasetSchema(
            "audit_events",
            "Synthetic platform audit activity.",
            (
                f(
                    "audit_event_id",
                    "string",
                    False,
                    "Stable audit event identifier.",
                    ID,
                    "AUD-000000001",
                ),
                f(
                    "actor_id",
                    "string",
                    False,
                    "Synthetic user/service actor.",
                    ID,
                    "SVC-SYNTHETIC-01",
                ),
                f(
                    "actor_role",
                    "string",
                    False,
                    "Synthetic platform role.",
                    GOVERNANCE,
                    "DATA_ENGINEER",
                ),
                f(
                    "action",
                    "string",
                    False,
                    "Controlled audit action.",
                    GOVERNANCE,
                    "READ",
                    "audit_action",
                ),
                f(
                    "object_type",
                    "string",
                    False,
                    "Audited object category.",
                    GOVERNANCE,
                    "DATASET",
                ),
                f(
                    "object_id",
                    "string",
                    False,
                    "Synthetic object reference.",
                    GOVERNANCE,
                    "patients",
                ),
                f(
                    "event_datetime",
                    "datetime",
                    False,
                    "Audit event time.",
                    GOVERNANCE,
                    "2024-01-01T00:00:00Z",
                ),
                f("outcome", "string", False, "Synthetic outcome.", GOVERNANCE, "SUCCESS"),
                f(
                    "source_component",
                    "string",
                    False,
                    "Synthetic component label.",
                    GOVERNANCE,
                    "GENERATOR",
                ),
                f(
                    "environment",
                    "string",
                    False,
                    "Non-secret environment label.",
                    GOVERNANCE,
                    "local",
                ),
                f(
                    "correlation_id",
                    "string",
                    False,
                    "Stable synthetic correlation identifier.",
                    GOVERNANCE,
                    "COR-000000001",
                ),
            ),
            ("audit_event_id",),
        ),
        "data_quality_events": DatasetSchema(
            "data_quality_events",
            "Deterministic register of intentionally injected defects.",
            (
                f(
                    "quality_event_id",
                    "string",
                    False,
                    "Stable quality event identifier.",
                    ID,
                    "DQE-000000001",
                ),
                f(
                    "dataset_name",
                    "string",
                    False,
                    "Affected canonical dataset.",
                    GOVERNANCE,
                    "appointments",
                ),
                f(
                    "rule_id",
                    "string",
                    False,
                    "Stable validation rule identifier.",
                    GOVERNANCE,
                    "BR-APT-001",
                ),
                f(
                    "rule_name",
                    "string",
                    False,
                    "Human-readable rule.",
                    GOVERNANCE,
                    "Cancelled appointment reason required",
                ),
                f(
                    "severity",
                    "string",
                    False,
                    "Controlled quality severity.",
                    GOVERNANCE,
                    "ERROR",
                    "quality_severity",
                ),
                f(
                    "record_identifier",
                    "string",
                    False,
                    "Affected synthetic record identifier.",
                    GOVERNANCE,
                    "APT-000000001",
                ),
                f(
                    "detected_at",
                    "datetime",
                    False,
                    "Deterministic detection timestamp.",
                    GOVERNANCE,
                    "2025-01-01T00:00:00Z",
                ),
                f("status", "string", False, "Quality workflow state.", GOVERNANCE, "OPEN"),
                f(
                    "resolution_action",
                    "string",
                    False,
                    "Expected remediation or test intent.",
                    GOVERNANCE,
                    "NEGATIVE_TEST_ONLY",
                ),
            ),
            ("quality_event_id",),
        ),
    }
)


def bf(
    name: str,
    data_type: str,
    nullable: bool,
    description: str,
    example: Any,
    code_set: str | None = None,
    classification: str = FINANCIAL,
) -> FieldSpec:
    return f(name, data_type, nullable, description, classification, example, code_set)


SCHEMAS.update(
    {
        "payers": DatasetSchema(
            "payers",
            "Synthetic healthcare billing payers.",
            (
                bf(
                    "payer_id",
                    "string",
                    False,
                    "Stable payer identifier.",
                    "PAYR-000000001",
                    classification=ID,
                ),
                bf(
                    "payer_code",
                    "string",
                    False,
                    "Synthetic payer code.",
                    "SYN-PAYR-001",
                    classification=PUBLIC,
                ),
                bf(
                    "payer_name",
                    "string",
                    False,
                    "Obviously synthetic payer name.",
                    "Synthetic Commissioner 001",
                    classification=PUBLIC,
                ),
                bf(
                    "payer_type",
                    "string",
                    False,
                    "Synthetic payer type.",
                    "COMMISSIONER",
                    "payer_type",
                ),
                bf(
                    "organisation_id",
                    "string",
                    True,
                    "Linked organisation where applicable.",
                    "ORG-000000001",
                ),
                bf("active_flag", "boolean", False, "Whether payer is active.", True),
                bf("valid_from", "date", False, "Effective start date.", "2021-01-01"),
                bf("valid_to", "date", True, "Effective end date.", None),
                bf("source_system", "string", False, "Synthetic billing source.", "SYN-BILLING"),
                bf(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    "2025-01-01T09:00:00Z",
                ),
            ),
            ("payer_id",),
            (ForeignKey(("organisation_id",), "organisations", ("organisation_id",)),),
        ),
        "services": DatasetSchema(
            "services",
            "Synthetic service catalogue.",
            (
                bf(
                    "service_id",
                    "string",
                    False,
                    "Stable service identifier.",
                    "SRV-000000001",
                    classification=ID,
                ),
                bf(
                    "service_code",
                    "string",
                    False,
                    "Synthetic service code.",
                    "SYN-SRV-001",
                    classification=PUBLIC,
                ),
                bf(
                    "service_name",
                    "string",
                    False,
                    "Synthetic service name.",
                    "Synthetic consultation",
                    classification=PUBLIC,
                ),
                bf(
                    "service_category",
                    "string",
                    False,
                    "Service category.",
                    "CONSULTATION",
                    "service_category",
                ),
                bf("specialty", "string", False, "Specialty.", "GENERAL_MEDICINE", "specialty"),
                bf("billable_flag", "boolean", False, "Whether service is billable.", True),
                bf("active_flag", "boolean", False, "Whether service is active.", True),
                bf("valid_from", "date", False, "Effective start.", "2021-01-01"),
                bf("valid_to", "date", True, "Effective end.", None),
                bf("source_system", "string", False, "Synthetic billing source.", "SYN-BILLING"),
                bf(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    "2025-01-01T09:00:00Z",
                ),
            ),
            ("service_id",),
        ),
        "products": DatasetSchema(
            "products",
            "Synthetic product catalogue.",
            (
                bf(
                    "product_id",
                    "string",
                    False,
                    "Stable product identifier.",
                    "PRD-000000001",
                    classification=ID,
                ),
                bf(
                    "product_code",
                    "string",
                    False,
                    "Synthetic product code.",
                    "SYN-PRD-001",
                    classification=PUBLIC,
                ),
                bf(
                    "product_name",
                    "string",
                    False,
                    "Synthetic product name.",
                    "Synthetic diagnostic kit",
                    classification=PUBLIC,
                ),
                bf(
                    "product_category",
                    "string",
                    False,
                    "Product category.",
                    "DIAGNOSTIC_KIT",
                    "product_category",
                ),
                bf("unit_of_measure", "string", False, "Unit of measure.", "EACH"),
                bf("billable_flag", "boolean", False, "Whether product is billable.", True),
                bf("active_flag", "boolean", False, "Whether product is active.", True),
                bf("valid_from", "date", False, "Effective start.", "2021-01-01"),
                bf("valid_to", "date", True, "Effective end.", None),
                bf("source_system", "string", False, "Synthetic billing source.", "SYN-BILLING"),
                bf(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    "2025-01-01T09:00:00Z",
                ),
            ),
            ("product_id",),
        ),
        "tariffs": DatasetSchema(
            "tariffs",
            "Synthetic source tariff records.",
            (
                bf(
                    "tariff_id",
                    "string",
                    False,
                    "Stable tariff identifier.",
                    "TRF-000000001",
                    classification=ID,
                ),
                bf(
                    "tariff_code",
                    "string",
                    False,
                    "Synthetic tariff code.",
                    "SYN-TRF-001",
                    classification=PUBLIC,
                ),
                bf("service_id", "string", False, "Referenced service.", "SRV-000000001"),
                bf("product_id", "string", True, "Optional product.", None),
                bf("payer_type", "string", False, "Payer type.", "COMMISSIONER", "payer_type"),
                bf("specialty", "string", False, "Specialty.", "GENERAL_MEDICINE", "specialty"),
                bf("currency", "string", False, "Currency.", "GBP", "currency"),
                bf("unit_price", "number", False, "Synthetic source unit price.", "120.00"),
                bf("valid_from", "date", False, "Effective start.", "2021-01-01"),
                bf("valid_to", "date", True, "Effective end.", None),
                bf("active_flag", "boolean", False, "Whether tariff is active.", True),
                bf("version", "integer", False, "Source tariff version.", 1),
                bf("source_system", "string", False, "Synthetic billing source.", "SYN-BILLING"),
                bf(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    "2025-01-01T09:00:00Z",
                ),
            ),
            ("tariff_id",),
            (
                ForeignKey(("service_id",), "services", ("service_id",)),
                ForeignKey(("product_id",), "products", ("product_id",)),
            ),
        ),
        "contracts": DatasetSchema(
            "contracts",
            "Synthetic payer-provider contracts.",
            (
                bf(
                    "contract_id",
                    "string",
                    False,
                    "Stable contract identifier.",
                    "CTR-000000001",
                    classification=ID,
                ),
                bf(
                    "contract_code",
                    "string",
                    False,
                    "Synthetic contract code.",
                    "SYN-CTR-001",
                    classification=PUBLIC,
                ),
                bf("payer_id", "string", False, "Payer.", "PAYR-000000001"),
                bf(
                    "provider_organisation_id",
                    "string",
                    False,
                    "Provider organisation.",
                    "ORG-000000001",
                ),
                bf(
                    "contract_type",
                    "string",
                    False,
                    "Contract type.",
                    "COMMISSIONER",
                    "contract_type",
                ),
                bf("valid_from", "date", False, "Effective start.", "2021-01-01"),
                bf("valid_to", "date", True, "Effective end.", None),
                bf("currency", "string", False, "Currency.", "GBP", "currency"),
                bf("payment_terms_days", "integer", False, "Payment terms.", 30),
                bf("pricing_basis", "string", False, "Pricing basis.", "TARIFF", "pricing_basis"),
                bf("status", "string", False, "Contract status.", "ACTIVE"),
                bf("source_system", "string", False, "Synthetic billing source.", "SYN-BILLING"),
                bf(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    "2025-01-01T09:00:00Z",
                ),
            ),
            ("contract_id",),
            (
                ForeignKey(("payer_id",), "payers", ("payer_id",)),
                ForeignKey(("provider_organisation_id",), "organisations", ("organisation_id",)),
            ),
        ),
        "billable_activity": DatasetSchema(
            "billable_activity",
            "Synthetic billable source activity linked to healthcare events.",
            (
                bf(
                    "billable_activity_id",
                    "string",
                    False,
                    "Stable billable activity identifier.",
                    "BACT-000000001",
                    classification=ID,
                ),
                bf("patient_id", "string", False, "Patient.", "PAT-000000001"),
                bf("encounter_id", "string", True, "Encounter.", "ENC-000000001"),
                bf("appointment_id", "string", True, "Appointment.", None),
                bf("clinical_event_id", "string", True, "Clinical event.", None),
                bf("service_id", "string", False, "Service.", "SRV-000000001"),
                bf("product_id", "string", True, "Product.", None),
                bf("provider_id", "string", False, "Provider.", "PRV-000000001"),
                bf("organisation_id", "string", False, "Organisation.", "ORG-000000001"),
                bf(
                    "activity_datetime",
                    "datetime",
                    False,
                    "Activity timestamp.",
                    "2024-01-01T09:00:00Z",
                ),
                bf("quantity", "number", False, "Source quantity.", "1.00"),
                bf("unit_of_measure", "string", False, "Unit of measure.", "EACH"),
                bf(
                    "billing_status",
                    "string",
                    False,
                    "Billing status.",
                    "INVOICED",
                    "billing_status",
                ),
                bf("source_system", "string", False, "Synthetic billing source.", "SYN-BILLING"),
                bf(
                    "source_record_id",
                    "string",
                    False,
                    "Healthcare source record.",
                    "ENC-000000001",
                ),
                bf(
                    "updated_at",
                    "datetime",
                    False,
                    "Synthetic last update.",
                    "2025-01-01T09:00:00Z",
                ),
            ),
            ("billable_activity_id",),
            (
                ForeignKey(("patient_id",), "patients", ("patient_id",)),
                ForeignKey(("encounter_id",), "encounters", ("encounter_id",)),
                ForeignKey(("appointment_id",), "appointments", ("appointment_id",)),
                ForeignKey(("clinical_event_id",), "clinical_events", ("clinical_event_id",)),
                ForeignKey(("service_id",), "services", ("service_id",)),
                ForeignKey(("product_id",), "products", ("product_id",)),
                ForeignKey(("provider_id",), "providers", ("provider_id",)),
                ForeignKey(("organisation_id",), "organisations", ("organisation_id",)),
            ),
        ),
    }
)

for _name, _fields, _pk, _fks in (
    (
        "claims",
        (
            "claim_id",
            "claim_number",
            "patient_id",
            "encounter_id",
            "payer_id",
            "contract_id",
            "claim_date",
            "service_period_start",
            "service_period_end",
            "claim_status",
            "currency",
            "claimed_amount",
            "submitted_at",
            "adjudicated_at",
            "rejection_code",
            "source_system",
            "updated_at",
        ),
        "claim_id",
        (
            ("patient_id", "patients", "patient_id"),
            ("encounter_id", "encounters", "encounter_id"),
            ("payer_id", "payers", "payer_id"),
            ("contract_id", "contracts", "contract_id"),
        ),
    ),
    (
        "claim_lines",
        (
            "claim_line_id",
            "claim_id",
            "billable_activity_id",
            "service_id",
            "product_id",
            "tariff_id",
            "quantity",
            "unit_price",
            "line_amount",
            "line_status",
            "rejection_code",
            "source_system",
            "updated_at",
        ),
        "claim_line_id",
        (
            ("claim_id", "claims", "claim_id"),
            ("billable_activity_id", "billable_activity", "billable_activity_id"),
            ("service_id", "services", "service_id"),
            ("product_id", "products", "product_id"),
            ("tariff_id", "tariffs", "tariff_id"),
        ),
    ),
    (
        "invoices",
        (
            "invoice_id",
            "invoice_number",
            "payer_id",
            "patient_id",
            "encounter_id",
            "contract_id",
            "invoice_date",
            "due_date",
            "invoice_status",
            "currency",
            "subtotal_amount",
            "tax_amount",
            "total_amount",
            "source_system",
            "updated_at",
        ),
        "invoice_id",
        (
            ("payer_id", "payers", "payer_id"),
            ("patient_id", "patients", "patient_id"),
            ("encounter_id", "encounters", "encounter_id"),
            ("contract_id", "contracts", "contract_id"),
        ),
    ),
    (
        "invoice_lines",
        (
            "invoice_line_id",
            "invoice_id",
            "billable_activity_id",
            "claim_line_id",
            "service_id",
            "product_id",
            "tariff_id",
            "description",
            "quantity",
            "unit_price",
            "net_amount",
            "tax_amount",
            "gross_amount",
            "source_system",
            "updated_at",
        ),
        "invoice_line_id",
        (
            ("invoice_id", "invoices", "invoice_id"),
            ("billable_activity_id", "billable_activity", "billable_activity_id"),
            ("claim_line_id", "claim_lines", "claim_line_id"),
            ("service_id", "services", "service_id"),
            ("product_id", "products", "product_id"),
            ("tariff_id", "tariffs", "tariff_id"),
        ),
    ),
    (
        "payment_attempts",
        (
            "payment_attempt_id",
            "invoice_id",
            "payer_id",
            "attempt_datetime",
            "payment_method",
            "requested_amount",
            "attempt_status",
            "failure_code",
            "gateway_reference",
            "idempotency_key",
            "source_system",
            "updated_at",
        ),
        "payment_attempt_id",
        (("invoice_id", "invoices", "invoice_id"), ("payer_id", "payers", "payer_id")),
    ),
    (
        "payments",
        (
            "payment_id",
            "payment_attempt_id",
            "invoice_id",
            "payer_id",
            "payment_datetime",
            "amount",
            "currency",
            "payment_method",
            "payment_status",
            "external_reference",
            "source_system",
            "updated_at",
        ),
        "payment_id",
        (
            ("payment_attempt_id", "payment_attempts", "payment_attempt_id"),
            ("invoice_id", "invoices", "invoice_id"),
            ("payer_id", "payers", "payer_id"),
        ),
    ),
    (
        "refunds",
        (
            "refund_id",
            "payment_id",
            "invoice_id",
            "refund_datetime",
            "refund_amount",
            "refund_reason",
            "refund_status",
            "source_system",
            "updated_at",
        ),
        "refund_id",
        (("payment_id", "payments", "payment_id"), ("invoice_id", "invoices", "invoice_id")),
    ),
    (
        "adjustments",
        (
            "adjustment_id",
            "invoice_id",
            "claim_id",
            "adjustment_type",
            "adjustment_reason",
            "adjustment_datetime",
            "adjustment_amount",
            "currency",
            "status",
            "source_system",
            "updated_at",
        ),
        "adjustment_id",
        (("invoice_id", "invoices", "invoice_id"), ("claim_id", "claims", "claim_id")),
    ),
    (
        "billing_exceptions",
        (
            "exception_id",
            "exception_type",
            "source_system",
            "source_record_id",
            "patient_id",
            "encounter_id",
            "billable_activity_id",
            "claim_id",
            "invoice_id",
            "payment_id",
            "severity",
            "financial_value_at_risk",
            "detected_at",
            "assigned_owner",
            "status",
            "resolution_date",
            "root_cause",
            "remediation_action",
            "synthetic_flag",
        ),
        "exception_id",
        (
            ("patient_id", "patients", "patient_id"),
            ("encounter_id", "encounters", "encounter_id"),
            ("billable_activity_id", "billable_activity", "billable_activity_id"),
            ("claim_id", "claims", "claim_id"),
            ("invoice_id", "invoices", "invoice_id"),
            ("payment_id", "payments", "payment_id"),
        ),
    ),
    (
        "revenue_events",
        (
            "revenue_event_id",
            "invoice_id",
            "invoice_line_id",
            "claim_id",
            "billable_activity_id",
            "event_type",
            "event_datetime",
            "amount",
            "currency",
            "source_status",
            "source_system",
            "updated_at",
        ),
        "revenue_event_id",
        (
            ("invoice_id", "invoices", "invoice_id"),
            ("invoice_line_id", "invoice_lines", "invoice_line_id"),
            ("claim_id", "claims", "claim_id"),
            ("billable_activity_id", "billable_activity", "billable_activity_id"),
        ),
    ),
    (
        "outstanding_balances",
        (
            "balance_snapshot_id",
            "invoice_id",
            "snapshot_date",
            "invoiced_amount",
            "payment_amount",
            "refund_amount",
            "adjustment_amount",
            "outstanding_amount",
            "ageing_bucket",
            "currency",
            "source_system",
            "updated_at",
        ),
        "balance_snapshot_id",
        (("invoice_id", "invoices", "invoice_id"),),
    ),
    (
        "daily_control_totals",
        (
            "control_total_id",
            "control_date",
            "source_system",
            "entity_type",
            "record_count",
            "gross_amount",
            "net_amount",
            "payment_amount",
            "refund_amount",
            "adjustment_amount",
            "currency",
            "generated_at",
            "checksum",
        ),
        "control_total_id",
        (),
    ),
):
    SCHEMAS[_name] = DatasetSchema(
        _name,
        f"Synthetic billing source dataset {_name}.",
        tuple(
            bf(
                _field,
                "number"
                if _field.endswith("_amount")
                or _field
                in {
                    "quantity",
                    "unit_price",
                    "line_amount",
                    "net_amount",
                    "gross_amount",
                    "tax_amount",
                    "claimed_amount",
                    "requested_amount",
                    "amount",
                    "invoiced_amount",
                    "payment_amount",
                    "refund_amount",
                    "adjustment_amount",
                    "outstanding_amount",
                    "financial_value_at_risk",
                }
                else "integer"
                if _field in {"record_count"}
                else "boolean"
                if _field == "synthetic_flag"
                else "date"
                if _field.endswith("_date")
                or _field == "snapshot_date"
                or _field == "control_date"
                or _field == "resolution_date"
                else "datetime"
                if _field.endswith("_at")
                or _field.endswith("_datetime")
                or _field in {"generated_at", "detected_at"}
                else "string",
                _field
                in {
                    "encounter_id",
                    "product_id",
                    "clinical_event_id",
                    "claim_line_id",
                    "payment_id",
                    "claim_id",
                    "invoice_id",
                    "invoice_line_id",
                    "billable_activity_id",
                    "patient_id",
                    "rejection_code",
                    "failure_code",
                    "resolution_date",
                    "root_cause",
                    "remediation_action",
                },
                f"Synthetic billing field {_field}.",
                None,
                "claim_status"
                if _field == "claim_status"
                else "claim_line_status"
                if _field == "line_status"
                else "invoice_status"
                if _field == "invoice_status"
                else "payment_attempt_status"
                if _field == "attempt_status"
                else "payment_status"
                if _field == "payment_status"
                else "payment_method"
                if _field == "payment_method"
                else "refund_status"
                if _field == "refund_status"
                else "adjustment_type"
                if _field == "adjustment_type"
                else "billing_exception_type"
                if _field == "exception_type"
                else "quality_severity"
                if _field == "severity"
                else "revenue_event_type"
                if _field == "event_type"
                else "ageing_bucket"
                if _field == "ageing_bucket"
                else "currency"
                if _field == "currency"
                else None,
                ID if _field == _pk or _field.endswith("_id") else FINANCIAL,
            )
            for _field in _fields
        ),
        (_pk,),
        tuple(ForeignKey((_field,), _dataset, (_ref,)) for _field, _dataset, _ref in _fks),
    )

DATASET_ORDER = tuple(SCHEMAS)
