"""Portfolio-oriented synthetic code sets; not authoritative NHS reference data."""

ORGANISATION_TYPES = (
    "TRUST",
    "HOSPITAL",
    "COMMUNITY_PROVIDER",
    "GP_PRACTICE",
    "LABORATORY",
    "RESEARCH_ORGANISATION",
)
LOCATION_TYPES = ("HOSPITAL_SITE", "WARD", "CLINIC", "DIAGNOSTIC", "LABORATORY", "VIRTUAL")
PROVIDER_ROLES = ("CONSULTANT", "NURSE", "AHP", "GP", "LAB_STAFF", "ADMINISTRATOR")
SPECIALTIES = ("GENERAL_MEDICINE", "CARDIOLOGY", "ORTHOPAEDICS", "ONCOLOGY", "PATHOLOGY")
SEX_CODES = ("FEMALE", "MALE", "INTERSEX", "NOT_KNOWN")
ETHNICITY_CODES = ("ASIAN", "BLACK", "MIXED", "WHITE", "OTHER", "NOT_STATED")
ENCOUNTER_TYPES = ("EMERGENCY", "INPATIENT", "OUTPATIENT", "COMMUNITY", "VIRTUAL")
ENCOUNTER_STATUSES = ("COMPLETED", "IN_PROGRESS", "CANCELLED")
APPOINTMENT_STATUSES = ("ATTENDED", "DID_NOT_ATTEND", "CANCELLED", "BOOKED")
PATHWAY_STATUSES = ("ACTIVE", "COMPLETED", "CANCELLED", "TRANSFERRED")
PATHWAY_STAGES = (
    "REFERRAL_RECEIVED",
    "TRIAGED",
    "BOOKED",
    "DIAGNOSTIC_TEST_PENDING",
    "TREATMENT_DECISION",
    "ADMITTED",
    "NON_ADMITTED_TREATMENT",
    "COMPLETED",
    "CANCELLED",
    "TRANSFERRED",
)
CONSENT_STATUSES = ("ACTIVE", "WITHDRAWN", "EXPIRED", "DECLINED")
CLINICAL_EVENT_TYPES = (
    "OBSERVATION",
    "DIAGNOSIS",
    "PROCEDURE",
    "REFERRAL",
    "ASSESSMENT",
    "TREATMENT_DECISION",
)
MEDICATION_EVENT_TYPES = ("PRESCRIPTION", "ADMINISTRATION", "DISCONTINUATION", "REVIEW")
PATHOLOGY_STATUSES = ("FINAL", "PRELIMINARY", "CORRECTED")
AUDIT_ACTIONS = ("READ", "CREATE", "UPDATE", "EXPORT_REQUEST", "LOGIN")
QUALITY_SEVERITIES = ("INFO", "WARNING", "ERROR", "CRITICAL")

ALL_CODE_SETS: dict[str, tuple[str, ...]] = {
    "organisation_type": ORGANISATION_TYPES,
    "location_type": LOCATION_TYPES,
    "provider_role": PROVIDER_ROLES,
    "specialty": SPECIALTIES,
    "sex": SEX_CODES,
    "ethnicity": ETHNICITY_CODES,
    "encounter_type": ENCOUNTER_TYPES,
    "encounter_status": ENCOUNTER_STATUSES,
    "attendance_status": APPOINTMENT_STATUSES,
    "pathway_status": PATHWAY_STATUSES,
    "pathway_stage": PATHWAY_STAGES,
    "consent_status": CONSENT_STATUSES,
    "clinical_event_type": CLINICAL_EVENT_TYPES,
    "medication_event_type": MEDICATION_EVENT_TYPES,
    "pathology_status": PATHOLOGY_STATUSES,
    "audit_action": AUDIT_ACTIONS,
    "quality_severity": QUALITY_SEVERITIES,
}
