"""Portfolio-oriented synthetic code sets; not authoritative NHS reference data."""

ORGANISATION_TYPES = (
    "TRUST",
    "HOSPITAL",
    "COMMUNITY_PROVIDER",
    "GP_PRACTICE",
    "LABORATORY",
    "RESEARCH_ORGANISATION",
)
LOCATION_TYPES = ("HOSPITAL_SITE", "WARD", "CLINIC", "DIAGNOSTIC", "LABORATORY", "VIRTUAL")
PROVIDER_ROLES = ("CONSULTANT", "NURSE", "AHP", "GP", "LAB_STAFF", "ADMINISTRATOR")
SPECIALTIES = ("GENERAL_MEDICINE", "CARDIOLOGY", "ORTHOPAEDICS", "ONCOLOGY", "PATHOLOGY")
SEX_CODES = ("FEMALE", "MALE", "INTERSEX", "NOT_KNOWN")
ETHNICITY_CODES = ("ASIAN", "BLACK", "MIXED", "WHITE", "OTHER", "NOT_STATED")
ENCOUNTER_TYPES = ("EMERGENCY", "INPATIENT", "OUTPATIENT", "COMMUNITY", "VIRTUAL")
ENCOUNTER_STATUSES = ("COMPLETED", "IN_PROGRESS", "CANCELLED")
APPOINTMENT_STATUSES = ("ATTENDED", "DID_NOT_ATTEND", "CANCELLED", "BOOKED")
PATHWAY_STATUSES = ("ACTIVE", "COMPLETED", "CANCELLED", "TRANSFERRED")
PATHWAY_STAGES = (
    "REFERRAL_RECEIVED",
    "TRIAGED",
    "BOOKED",
    "DIAGNOSTIC_TEST_PENDING",
    "TREATMENT_DECISION",
    "ADMITTED",
    "NON_ADMITTED_TREATMENT",
    "COMPLETED",
    "CANCELLED",
    "TRANSFERRED",
)
CONSENT_STATUSES = ("ACTIVE", "WITHDRAWN", "EXPIRED", "DECLINED")
CLINICAL_EVENT_TYPES = (
    "OBSERVATION",
    "DIAGNOSIS",
    "PROCEDURE",
    "REFERRAL",
    "ASSESSMENT",
    "TREATMENT_DECISION",
)
MEDICATION_EVENT_TYPES = ("PRESCRIPTION", "ADMINISTRATION", "DISCONTINUATION", "REVIEW")
PATHOLOGY_STATUSES = ("FINAL", "PRELIMINARY", "CORRECTED")
AUDIT_ACTIONS = ("READ", "CREATE", "UPDATE", "EXPORT_REQUEST", "LOGIN")
QUALITY_SEVERITIES = ("INFO", "WARNING", "ERROR", "CRITICAL")
PAYER_TYPES = ("COMMISSIONER", "INSURER", "SELF_PAY", "CORPORATE", "RESEARCH_SPONSOR", "OTHER")
SERVICE_CATEGORIES = (
    "CONSULTATION",
    "DIAGNOSTIC_TEST",
    "PROCEDURE",
    "TREATMENT",
    "BED_DAY",
    "MEDICATION_SERVICE",
    "VIRTUAL_CONSULTATION",
    "ADMINISTRATIVE",
)
PRODUCT_CATEGORIES = (
    "CONSUMABLE",
    "MEDICAL_DEVICE",
    "MEDICATION_PRODUCT",
    "DIAGNOSTIC_KIT",
    "CARE_PACKAGE",
)
CONTRACT_TYPES = ("COMMISSIONER", "INSURER", "SELF_PAY", "CORPORATE", "RESEARCH")
PRICING_BASES = ("TARIFF", "CONTRACT_RATE", "SOURCE_LIST_PRICE")
CLAIM_STATUSES = ("DRAFT", "SUBMITTED", "ACCEPTED", "REJECTED", "PAID")
CLAIM_LINE_STATUSES = ("SUBMITTED", "ACCEPTED", "REJECTED")
INVOICE_STATUSES = ("DRAFT", "ISSUED", "PART_PAID", "PAID", "CANCELLED")
PAYMENT_ATTEMPT_STATUSES = ("REQUESTED", "SUCCESS", "FAILED")
PAYMENT_STATUSES = ("POSTED", "REVERSED")
PAYMENT_METHODS = ("SYNTHETIC_CARD", "BANK_TRANSFER", "DIRECT_DEBIT", "INTERNAL_TRANSFER")
REFUND_STATUSES = ("REQUESTED", "PAID", "REJECTED")
ADJUSTMENT_TYPES = ("CREDIT", "DEBIT", "WRITE_OFF", "CONTRACTUAL", "CORRECTION")
BILLING_EXCEPTION_TYPES = (
    "COMPLETED_ACTIVITY_WITHOUT_INVOICE",
    "MISSING_TARIFF",
    "EXPIRED_TARIFF",
    "DUPLICATE_CLAIM",
    "DUPLICATE_INVOICE",
    "INVOICE_WITHOUT_LINES",
    "PAYMENT_WITHOUT_INVOICE",
    "PAYMENT_FAILURE",
    "INCORRECT_CONTRACT_RATE",
    "REFUND_GREATER_THAN_PAYMENT",
    "MISSING_PAYER",
    "REJECTED_CLAIM",
    "LATE_PAYMENT",
    "INVALID_ADJUSTMENT",
    "CURRENCY_MISMATCH",
    "UNALLOCATED_PAYMENT",
)
REVENUE_EVENT_TYPES = ("BILLED", "COLLECTED", "REFUNDED", "ADJUSTED", "WRITTEN_OFF")
AGEING_BUCKETS = ("CURRENT", "DAYS_1_30", "DAYS_31_60", "DAYS_61_90", "DAYS_90_PLUS")
CURRENCIES = ("GBP",)
BILLING_STATUSES = ("IDENTIFIED", "CLAIMED", "INVOICED", "PAID", "EXCEPTION")

ALL_CODE_SETS: dict[str, tuple[str, ...]] = {
    "organisation_type": ORGANISATION_TYPES,
    "location_type": LOCATION_TYPES,
    "provider_role": PROVIDER_ROLES,
    "specialty": SPECIALTIES,
    "sex": SEX_CODES,
    "ethnicity": ETHNICITY_CODES,
    "encounter_type": ENCOUNTER_TYPES,
    "encounter_status": ENCOUNTER_STATUSES,
    "attendance_status": APPOINTMENT_STATUSES,
    "pathway_status": PATHWAY_STATUSES,
    "pathway_stage": PATHWAY_STAGES,
    "consent_status": CONSENT_STATUSES,
    "clinical_event_type": CLINICAL_EVENT_TYPES,
    "medication_event_type": MEDICATION_EVENT_TYPES,
    "pathology_status": PATHOLOGY_STATUSES,
    "audit_action": AUDIT_ACTIONS,
    "quality_severity": QUALITY_SEVERITIES,
    "payer_type": PAYER_TYPES,
    "service_category": SERVICE_CATEGORIES,
    "product_category": PRODUCT_CATEGORIES,
    "contract_type": CONTRACT_TYPES,
    "pricing_basis": PRICING_BASES,
    "claim_status": CLAIM_STATUSES,
    "claim_line_status": CLAIM_LINE_STATUSES,
    "invoice_status": INVOICE_STATUSES,
    "payment_attempt_status": PAYMENT_ATTEMPT_STATUSES,
    "payment_status": PAYMENT_STATUSES,
    "payment_method": PAYMENT_METHODS,
    "refund_status": REFUND_STATUSES,
    "adjustment_type": ADJUSTMENT_TYPES,
    "billing_exception_type": BILLING_EXCEPTION_TYPES,
    "revenue_event_type": REVENUE_EVENT_TYPES,
    "ageing_bucket": AGEING_BUCKETS,
    "currency": CURRENCIES,
    "billing_status": BILLING_STATUSES,
}
