name: Documentation and YAML

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: "**/*.md"
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_file: .yamllint
